---
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "07:00"
      timezone: "Europe/Rome"
    rebase-strategy: "disabled"
    groups:
      cargo:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:00"
      timezone: "Europe/Rome"
